services:
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: job-portal
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
